AWSAccountID: "216211142709"
AWSProfileName: "cameronguy-biz-dev"
AWSProfileRegion: "eu-west-2"

App: "CameronGuy-biz"
Prefix: "cameronguy-biz"

CorsServer: http://localhost:3000
DomainName: cameronguy.biz
ApiDomainName: dev.cameronguy.biz
DATABASEHOST: -arn
DATABASEUSER: 
DATABASEPASSWORD: 
DATABASENAME: 
DATABASEPORT: 
JWTSECRET: 
JWTREFRESHSECRET: 

 # Add for the database
    #  Dev:
    #   BackupRetentionPeriod: 0
    #   DeleteAutomatedBackups: true
    #   DeletionProtection: false
    #   DeletionPolicy: false
    #   MultiAZ: false
    # Prod:
    #   BackupRetentionPeriod: 7
    #   DeleteAutomatedBackups: false
    #   DeletionProtection: true
    #   MultiAZ: true
