name: "Deploy :: Dev"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

jobs:
  deploy:
    name: Load the baseline
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '18'

    - name: Install packages
      run: |
        yarn install

    - name: Install dependencies
      run: npm install -g aws-cdk

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::216211142709:role/AWSOpenIdRole
        aws-region: eu-west-2

    - name: Run build
      run: |
        cd apps/infrastructure
        yarn build

    # - name: Run Infratsructure Setup
    #   run: |
    #       cd apps/infrastructure
    #       cdk deploy -c setup=true --require-approval never

    - name: Run development cdk
      run: |
          cd apps/infrastructure
          cdk deploy -c env=dev --require-approval never
    
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Setup Node
      #   uses: actions/setup-node@v2-beta
      #   with:
      #     node-version: '18'
      # - name: Install packages
      #   run: |
      #     yarn install
      # - name: Install dependencies
      #   run: npm install -g aws-cdk

      # - name: Configure AWS credentials from Test account
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::216211142709:role/AWSOpenIdRole
      #     aws-region: eu-west-2

      # # - name: Configure AWS credentials from Test account
      # #   uses: aws-actions/configure-aws-credentials@v2
      # #   with:
      # #     role-to-assume: arn:aws:iam::216211142709:role/AWSOpenIdRole
      # #     aws-region: eu-west-2

      # - name: Build
      #   run: |
      #     cd apps/infrastructure
      #     yarn build
      # - name: Run cdk
      #   run: |
      #       cd apps/base-infrastructure
      #       cdk deploy -c setup=true --require-approval never
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "18.x"
      # - name: List
      #   run: ls -ltr
      # - name: Build Website and Zip
      #   run: ./.github/deploy/scripts/lint_test_build.sh
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: build.zip
      #     path: build.zip

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "18.x"

  #     - name: Deploy
  #       uses: